### ISSUE TITLE
Spelling mistake in test_avg_uppper_threshold_is_included

### ISSUE THREAD

**Issue by chtrac** [lgiordani/simple_calculator#1]
https://github.com/lgiordani/simple_calculator/blob/da3b88a743789ed4668981f8533094a11a7dd808/tests/test_main.py#L108

The function name `test_avg_uppper_threshold_is_included` is misspelled (three p instead of two).

**Comment by lgiordani** [comment]
Cristopher, thanks for spotting this. I fixed it and also updated the tags that were pointing to a slightly older branch (the README was different, nothing serious). This has also been fixed in the relative post on my blog. Thanks again!
